### ISSUE TITLE
Issue saving (semi) transparent tiles of a tileset

### ISSUE THREAD

**Issue by Zement** [NSMBW-Community/Puzzle-Updated#4]
Transparent or semi transparent tiles are encoded wrong, after saving the tileset.
Transparency is replaced by a grey color.

![puzzle-Updated-alpha-problem](https://user-images.githubusercontent.com/11998834/65821854-9eff7380-e23b-11e9-82a1-7417ee3e66a1.png)

**Comment by RoadrunnerWMC** [comment]
Thanks for making the issue.

I just tested it myself, and it seems to work more or less OK for me? Like I said on Discord, it'd be very helpful to have specific steps to reproduce this, such as the exact RGBA color values of those regions, or an actual PNG image that causes the issue to occur. Not sure I can do very much without something specific like that.

**Comment by Zement** [comment]
Ok, I've created a test image that consists of 4 vertical colored bars. The left-most bar has an opacity of 0%, then 25%, 50%, and 75%. It's not very easy to see, but you should be able to spot the differences when you open both files in an image viewer and scroll back and forth quickly (nvm it's actually easy to see). Basically what happens is, that the transparency is not "converted" 100% correctly. Instead, there is slightly less transparency, plus a grey hue.

Steps to reproduce the issue:
- Open Puzzle
- Import image (alpha_test.png)
- Save
- Close Puzzle (!)
- Open Puzzle and previously saved tileset
- Export image

It's important to note that *all* tilesets with (semi) transparent tiles are affected,

alpha_test.png
![alpha_test](https://user-images.githubusercontent.com/11998834/66035651-d1df8b00-e50b-11e9-8c3a-f5f2c73073b2.png)
alpha_test_After_save.png
![alpha_test_after_save](https://user-images.githubusercontent.com/11998834/66035650-d146f480-e50b-11e9-8215-acbd9637488a.png)

**Comment by RoadrunnerWMC** [comment]
Thank you! Commit 262f0366c5d3e3194afc9cd50c16da75ae96dbc6 should fix the issue. I'm not sure exactly why, though, since I simply undid something that supposedly increased accuracy in the past. It's definitely much more accurate now, though, so I'm comfortable with leaving it like this for now.

**Comment by Zement** [comment]
Thanks very much RoadrunnerWMC, the issue seems to be solved. I've done the above steps again and compared the output image with the one created from Puzzle 0.8, and they are identical. Same with my personal tilesets.

You should maybe add a note to readme.md saying that users should check their tilesets, if they made them using the previous commit.

I'd also like to mention that the images *still* lose a bit of transparency each time they are saved, but this is more of a general problem, as it affects *all* Puzzle versions I've tested this with (0.6, 0.8, old src, Puzzle-Updated). Maybe it can't be fixed at all.

**Comment by RoadrunnerWMC** [comment]
I'm a bit hesitant to declare that accuracy has definitely increased with this commit. It does seem to help with this test case (and the other ones you referred to), but this commit only undoes a change that seemed to help other tilesets at the time. I have a feeling there might be a deeper issue here, like "different PNGs use different color spaces, which is confusing Qt," but I'd have to do some more research by digging up those original test cases to know for sure.

----

Not sure exactly what you mean by that:

- If you mean "they become more opaque overall every time you save," and this holds true for lots of translucent colors, that's a problem.
- If you mean "the transparency becomes less accurate (or more opaque) every time you save and re-open the same tileset, causing it to become very wrong after multiple rounds of saving," that's also a problem. The quality should not decrease with repeated saving.
- But if you just mean mean "the accuracy of transparency decreases when saving," that's just because the alpha channel in RGB4A3 is only three bits wide (that is, every pixel's alpha value is stored in the file as a number between 0 and 7, which doesn't permit very much accuracy).

**Comment by Zement** [comment]
I'm pretty sure it is the third case. The image quality doesn't degrade over time, instead, the first time it is saved, the transparency is "simplified" due to the reason you explained (RGB5A3 using only 3 bits of transparency). I've experienced that over and over and had assumed the same thing, but was never really sure about it. So, thanks for clarifying!
